services:
  bot_wiretapping:
    build: .
    container_name: bot_wiretapping
    environment:
      - ENV_FILE=.env
    command: python bot.py
    volumes:
      - .:/app
    depends_on:
      - database
    network_mode: "host"
    restart: always
  database:
    image: postgres:15
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}