"""create tables

Revision ID: 21dc4a05c888
Revises: 
Create Date: 2024-10-31 21:31:49.335464

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "21dc4a05c888"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vk_users",
        sa.Column("vk_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("muth", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("vk_id", "id"),
        sa.UniqueConstraint("vk_id"),
    )
    op.create_table(
        "vk_user_numbres",
        sa.Column("id_user", sa.BigInteger(), nullable=False),
        sa.Column("number", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["id_user"],
            ["vk_users.vk_id"],
        ),
        sa.PrimaryKeyConstraint("id_user", "number", "id"),
        sa.UniqueConstraint("number"),
    )
    op.create_table(
        "vk_user_promocode",
        sa.Column("vk_id", sa.BigInteger(), nullable=False),
        sa.Column("promocode", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["vk_id"],
            ["vk_users.vk_id"],
        ),
        sa.PrimaryKeyConstraint("vk_id", "id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vk_user_promocode")
    op.drop_table("vk_user_numbres")
    op.drop_table("vk_users")
    # ### end Alembic commands ###
