"""add column name

Revision ID: e6dd7fbe79ef
Revises: 21dc4a05c888
Create Date: 2024-10-31 21:41:12.235796

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e6dd7fbe79ef"
down_revision: Union[str, None] = "21dc4a05c888"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vk_users", sa.Column("name", sa.String(length=255), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vk_users", "name")
    # ### end Alembic commands ###
