"""create add column create_at table vk_last_messages

Revision ID: 5dfdd4383bdd
Revises: 75a32e5e57c5
Create Date: 2024-11-03 17:13:32.754885

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5dfdd4383bdd"
down_revision: Union[str, None] = "75a32e5e57c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vk_last_messages",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vk_last_messages", "created_at")
    # ### end Alembic commands ###
